flowchart TB
    CENTER[("Server trung tam<br/>users global<br/>campaign master/shared<br/>stats global<br/>metadata/config lab")]

    subgraph BRANCH["4 server chi nhanh / 4 manh"]
        CN1[("CN1 Shard<br/>donations CN1<br/>payments CN1<br/>reports CN1")]
        CN2[("CN2 Shard<br/>donations CN2<br/>payments CN2<br/>reports CN2")]
        CN3[("CN3 Shard<br/>donations CN3<br/>payments CN3<br/>reports CN3")]
        CN4[("CN4 Shard<br/>donations CN4<br/>payments CN4<br/>reports CN4")]
    end

    CENTER -->|branchCode maps data| CN1
    CENTER -->|branchCode maps data| CN2
    CENTER -->|branchCode maps data| CN3
    CENTER -->|branchCode maps data| CN4

    CN1 -. aggregate verified .-> CENTER
    CN2 -. aggregate verified .-> CENTER
    CN3 -. aggregate verified .-> CENTER
    CN4 -. aggregate verified .-> CENTER
